### ISSUE TITLE
No funciona con las materias que se dan dos veces a la semana

### ISSUE THREAD

**Issue by Frilo** [nadiafaya/alternativity#10]
A partir del commit c50f7af92cc922b5edda5fee1cab8963acee2618 las materias cuatrimestrales que se dan dos veces a la semana no funcionan correctamente:

Por ejemplo, Matemática Superior tiene estos horarios:

  | K3051 | Lu(n)1:4 Ju(n)0:2 | CAMPUS
-- | -- | -- | --
  | K3012 | Ma(m)0:2 Vi(m)1:5 | MEDRANO
  | K3053 | Ma(n)0:2 Ju(n)1:5 | CAMPUS
  | K3054 | Ma(n)1:5 Mi(n)3:5 | CAMPUS
  | K3011 | Mi(m)3:6 Vi(m)3:6 | MEDRANO
  | K3052 | Mi(n)0:2 Ju(n)1:5 | CAMPUS

Debería aparecer esta tabla:

Lunes | Martes | Miércoles | Jueves | Viernes | Sábado | Horario habilitado
-- | -- | -- | -- | -- | -- | --
n 1:4 |   |   | n 1:2 |   |   | ONOFF
  | m 1:2 |   |   | m 1:5 |   | ONOFF
  | n 1:2 |   | n 1:5 |   |   | ONOFF
  | n 1:5 | n 3:5 |   |   |   | ONOFF
  |   | m 3:6 |   | m 3:6 |   | ONOFF
  |   | n 1:2 | n 1:5 |   |   | ONOFF

Pero muestra esta:

Lunes | Martes | Miércoles | Jueves | Viernes | Sábado | Horario habilitado
-- | -- | -- | -- | -- | -- | --
  |   |   | n 1:2 |   |   | ONOFF
  |   |   |   | m 1:5 |   | ONOFF
  |   |   | n 1:5 |   |   | ONOFF
  |   | n 3:5 |   |   |   | ONOFF
  |   |   |   | m 3:6 |   | ONOFF
  |   |   | n 1:5 |   |   | ONOFF

Pasa lo mismo con las otras cuatrimestrales.
Con las que son de un solo día no hay problema

**Comment by nadiafaya** [comment]
Buenas, muchas gracias por reportar este issue. Tenés razón, lo pude reproducir.

Creo que lo pude arreglar en este branch: https://github.com/nadiafaya/alternativity/tree/fix-issue-with-multiple-day-subjects. Lo testee bajo distintas condiciones y parece estar ok.

Si no te molesta testearlo antes que lo mergee, me vendría de 10 :) 

De nuevo, mil gracias por reportarlo!

**Comment by Frilo** [comment]
Hola, muchas gracias por arreglarlo tan rápido!

Testeado, todo funciona bien

**Comment by nadiafaya** [comment]
Genial! Muchísimas gracias por tu ayuda!
