### ISSUE TITLE
El titulo de las materias no se ven

### ISSUE THREAD

**Issue by FinderX** [nadiafaya/alternativity#5]
El titulo de las materias no se ven o estan en blanco con fondo blanco.

También no se pueden editar y/o borrar materias una vez cargadas.

**Comment by nadiafaya** [comment]
Mil gracias por probarlo. Te puedo preguntar con que navegador lo estas usando y si es posible mandarme un print screen para ver el error?

**Comment by FinderX** [comment]
Ok, uso el firefox, una cosa que me olvide comentar es que yo bloque las cookies de las paginas que no agrego a mi lista blanca. Capas pueda ser el problema?

![printsc_1](https://cloud.githubusercontent.com/assets/8683793/6418525/7a8c4d04-be94-11e4-8f14-17d2cc6d7ae7.jpg)
