### ISSUE TITLE
Codigo de curso en la pestaña de alternativas

### ISSUE THREAD

**Issue by rodrigo103** [nadiafaya/alternativity#7]
Esta aplicacion siempre me es muy util, por eso me gustaria proponer como mejora que en la pestaña donde se muestran las distintas alternativas se muestre sobre cada materia no solo el nombre, sino tambien el codigo de curso, ya que si se ingresara por ejemplo de la siguiente forma:
R5052(Ing.C.Navarro)	Lu(n)1:5	MEDRANO
R5053(Ing.C.Navarro)	Ju(n)1:5	MEDRANO
R5051(Ing.M.Seoane)	Vi(n)1:5	MEDRANO
Uno podria saber con que profesor y en que curso le tocaria cada materia en cada alternativa, haciendo de esta forma aun mas sencillo el proceso de seleccion.

**Comment by nadiafaya** [comment]
Buenas, me alegra mucho que esto se siga usando (y me entristece que el SIGA no haya cambiado ni un poquito 😢 ).

Está bueno lo que propones, lo que si intentando implementarlo, medio que tanta información hace que la tabla quede un poco grande, y por ahí no todos tienen diferentes códigos y profesores así que por ahí no es info relevante para todo el mundo.

Así que decidí ponerlo detrás de un botón de toggle para ver la tabla de siempre o una con más info.

También modifique un poco como se parsea la información de los horarios.

Si no te molesta me vendría bien si lo podes testear un poco antes de que lo mergee, solo por las dudas le haya pifiado a algo:

https://github.com/nadiafaya/alternativity/pull/8

Mil gracias!

**Comment by rodrigo103** [comment]
Quedo muy buena la implementacion, mil gracias a vos!! esta aplicacion siempre me ayuda un monton a evaluar las diferentes opciones y ahora aun mas 😁.
